### ISSUE TITLE
Responsive / HA Grid Support

### ISSUE THREAD

**Issue by timdonovanuk** [GeorgeSG/lovelace-time-picker-card#13]
All on latest HA and latest card. Doesn't display correctly on mobiles:

![image](https://user-images.githubusercontent.com/8156439/103283683-256fab80-49d1-11eb-9717-d5413f14ab53.png)

**Comment by timdonovanuk** [comment]
In a desktop browser, it totally breaks with the new grid system when using name inside:

![image](https://user-images.githubusercontent.com/8156439/103283796-6c5da100-49d1-11eb-8cb4-31f418544e38.png)

**Comment by GeorgeSG** [comment]
Thanks for the bug report, I'll try to take a look in the next couple of days! :)

**Comment by timdonovanuk** [comment]
No worries, I think part of this is the new grid system is also quiet buggy in HA!

Happy Holidays :)

**Comment by GeorgeSG** [comment]
Soo, a "couple of days later" 😅, I took a look at this.

The problem is that the grid system is forcing a max-width of the tile and there's not much the card can do about it (that's kinda the point of the Grid).

Even native Home Assistant cards are breaking. For example, here's the native Entities card:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/2514425/112731175-662e8080-8f3e-11eb-8547-3be554df82e0.png">

A quick solution I can think of (and will do for now), is hiding the card content and making it scrollable. In these cases, there will be horizontal scroller and you will be able to scroll to the controls (or on mobile - swipe). Not ideal, but that's the best I have for now 😅

I'm open for better ideas, if anyone has one :)

**Comment by GeorgeSG** [comment]
"Fix" released in [1.2.0](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.2.0)
