### ISSUE TITLE
Add a option to select Workday and Weekend.

### ISSUE THREAD

**Issue by anarro** [GeorgeSG/lovelace-time-picker-card#2]
Hi,

I love you card, but can you add a option to select a workday and weekend days, please?

and some example to use it with a automation?, it's possible?

Thanks,

**Comment by GeorgeSG** [comment]
Thanks! 

I'm not sure what you mean, how would you select workday or weekends for a time? Even if it was setting the date as well as the time, I still don't see how it would set workdays?

Can you give a more detailed explanation and examples of how you want to use this or how you expect it to work?

**Comment by GeorgeSG** [comment]
Ah, I think I see what you mean - You probably want to use this for an Alarm Clock, and that's why you want to be able to set Workdays and Weekend, correct?

If that's the case - this card is not an "Alarm Clock" card. I guess the example screenshots in the README mislead you.

This is a generic card for setting a [input Datetime](https://www.home-assistant.io/integrations/input_datetime/) value that can be used for anything. For example, you can use it to set a countdown timer. Input Datetime does not support weekdays/workdays on it's own. You have to implement it yourself on top of that.
